### ISSUE TITLE
How can I use Section3？

### ISSUE THREAD

**Issue by tearsness** [KJStrand/3D_Medical_Segmentation_HC#2]
How can I use Section3？

**Comment by KJStrand** [comment]
I have updated section 3 README to include instructions from Udacity course for replicating mock clinical network: [README](https://github.com/KJStrand/3D_Medical_Segmentation_Hippocampus/blob/master/Section3/README.md).

I used the Udacity workspace and did not verify these steps on my own environment.

Please be aware this is project is in no way intended for real clinical use!
